micronaut:
  application:
    name: micronaut4kotlin2kotestrestassured
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
    db-type: postgres
flyway:
  datasources:
    default:
      enabled: true
#problem:
#  typeBaseUri: http://docs.my-site.com/errors/
